In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Loading the Data set
df = pd.read_csv("/kaggle/input/datasets/rohitsahoo/sales-forecasting/train.csv")

In [26]:
df.head(2)

,Order ID,Order Date,Customer ID,Segment,Country,City,State,Region,Product ID,Category,Product Name,Sales
0,CA-2017-152156,2017-11-08,CG-12520,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bush Somerset Collection Bookcase,261.96
1,CA-2017-152156,2017-11-08,CG-12520,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [4]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [5]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9795    False
9796    False
9797    False
9798    False
9799    False
Length: 9800, dtype: bool

In [6]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

Row ID           0.000000
Order ID         0.000000
Order Date       0.000000
Ship Date        0.000000
Ship Mode        0.000000
Customer ID      0.000000
Customer Name    0.000000
Segment          0.000000
Country          0.000000
City             0.000000
State            0.000000
Postal Code      0.112245
Region           0.000000
Product ID       0.000000
Category         0.000000
Sub-Category     0.000000
Product Name     0.000000
Sales            0.000000
dtype: float64

In [8]:
df.drop(['Ship Date','Row ID','Ship Mode','Sub-Category','Postal Code','Customer Name'], axis=1, inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      9800 non-null   object
 1   Order Date    9800 non-null   object
 2   Customer ID   9800 non-null   object
 3   Segment       9800 non-null   object
 4   Country       9800 non-null   object
 5   City          9800 non-null   object
 6   State         9800 non-null   object
 7   Region        9800 non-null   object
 8   Product ID    9800 non-null   object
 9   Category      9800 non-null   object
 10  Product Name  9800 non-null   object
 11  Sales         9800 non-null   float64
dtypes: float64(1), object(11)
memory usage: 918.9+ KB

In [11]:
df.describe()

              Sales
count   9800.000000
mean     230.769059
std      626.651875
min        0.444000
25%       17.248000
50%       54.490000
75%      210.605000
max    22638.480000

In [12]:
df.head(2)

,Order ID,Order Date,Customer ID,Segment,Country,City,State,Region,Product ID,Category,Product Name,Sales
0,CA-2017-152156,08/11/2017,CG-12520,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bush Somerset Collection Bookcase,261.96
1,CA-2017-152156,08/11/2017,CG-12520,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94

In [13]:
df.shape

(9800, 12)

In [14]:
df.isnull().sum()

Order ID        0
Order Date      0
Customer ID     0
Segment         0
Country         0
City            0
State           0
Region          0
Product ID      0
Category        0
Product Name    0
Sales           0
dtype: int64

Convert Date

In [22]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      9800 non-null   object
 1   Order Date    9800 non-null   datetime64[ns]
 2   Customer ID   9800 non-null   object
 3   Segment       9800 non-null   object
 4   Country       9800 non-null   object
 5   City          9800 non-null   object
 6   State         9800 non-null   object
 7   Region        9800 non-null   object
 8   Product ID    9800 non-null   object
 9   Category      9800 non-null   object
 10  Product Name  9800 non-null   object
 11  Sales         9800 non-null   float64
dtypes: datetime64[ns](1), float64(1), object(10)
memory usage: 918.9+ KB

In [25]:
df.shape

(9800, 12)